const general = require('../routes/general.js');
const users = require('../routes/user.js');
const missions = require('../routes/mission.js');
const missionsAnswer = require('../routes/missionAnswer.js');
const quizzes = require('../routes/quiz.js');
const quizzesAnswer = require('../routes/quizAnswer.js');
const groups = require('../routes/group.js');
const groupMember = require('../routes/groupMember.js');
const post = require('../routes/post.js');
const reaction = require('../routes/reaction.js');
const tree = require('../routes/tree.js');
const treeRequest = require('../routes/treeRequest.js');
const treeType = require('../routes/treeType.js');
const appointment = require('../routes/appointment.js');
const appointmentRequest = require('../routes/appointmentRequest.js');
const places = require('../routes/place.js');
const analytics = require('../routes/analytics');

module.exports = app => {
  app.use('/general', general);
  app.use('/users', users);
  app.use('/missions', missions);
  app.use('/missions_answers', missionsAnswer);
  app.use('/quizzes', quizzes);
  app.use('/quiz_answers', quizzesAnswer);
  app.use('/groups', groups);
  app.use('/group_members', groupMember);
  app.use('/posts', post);
  app.use('/reactions', reaction);
  app.use('/trees', tree);
  app.use('/tree_requests', treeRequest);
  app.use('/tree_types', treeType);
  app.use('/appointment', appointment);
  app.use('/appointment_requests', appointmentRequest);
  app.use('/places', places);
  app.use('/analytics', analytics);
};
